### ISSUE TITLE
display FPS count

### ISSUE THREAD

**Issue by UgiNyaa** [htl22-3ahif/fun#3]
Sie kann sich überall befinden, Hauptsache sie behindert nicht die Sicht. Auch eine schöne Einführung in UI.

**Comment by ghost** [comment]
OpenTK.GameWindow class includes a "RenderFrequency" Property which takes away the calculating fps part of this problem!

**Comment by UgiNyaa** [comment]
After trying to show the fps on the hud we accidentally put it where it should not be. When you just activate the hudcomponent, you will see the fps displayed as texture on all meshes.

The binding of the fps texture happens in "update", but the right texture is binded in "initialize", so it prefers the fps texture. It is easy to solve. 

The real problem is situated in displaying the fps on the hud.
It is also connected with our shaders, so there are two solutions:
- Make a new shaderprogram only used for hud
- Use the current shaderprogram and give it special parameter to display it correctly

Both is possible i think (I am really not sure).
Just try some things out and maybe it will work.
If not, we have to analyse it more accurate.

**Comment by ghost** [comment]
"After trying to display the fps count on the hud we accidentally put it where it should not be. Upon activating HUD Component the fps texture starts replacing our previously used texture. 

The binding of the fps texture is done by "update", but our previous texture, the correct one gets bound by "initialize". Eventually, our original texture gets overwritten frequently by "update".

The real problem is displaying the fps count on the HUD.
The cause leads us to our shaders, there are two available solutions:

> Make a new shaderprogram solely used for the HUD
> Use the current shaderprogram with special parameters to display the textures respectively

Both should be doable (I am really not sure).
Just experiment and maybe it'll work.
If not, we'll have to look deeper into our problem."
is how I would write this comment.

**Comment by ghost** [comment]
The proper solution would be the implementation of a text render framework. 
To get started take a look at this example: 
https://github.com/giawa/opengl4tutorials/tree/master/OpenGLTutorial10
